experiment:
  args:
    project: ZERO
    entity: alan0220
    name: ModalSpecZERO_infonce_30learnable_token #每次實驗應該更改 

dataset:
  type: VAST27MDataset
  args:
    dataset_folder: /home/miislab-server2/Alan/dataset/vast27m/video_feature
    features_to_load: ['CLIP']
    captions_to_load: ['vision_cap']
    test_size: 0.1 # test data的比例
    random_state: 42  # 分割資料集的隨機種子

collate_fn:
  type: CustomCollateFn
  args: 
    tokenizer_model_name: google/flan-t5-xl
    use_fast: True

train_loader:
  type: DataLoader
  args:
    batch_size: 128
    num_workers: 8
    pin_memory: True
    shuffle: True

eval_loader:
  type: DataLoader
  args:
    batch_size: 128
    num_workers: 8
    pin_memory: True
    shuffle: False

model:
  type: ModalSpecZERO
  args:
    embedding_dim: 512
    num_heads: 8
    ff_hidden_dim: 1024
    learnable_token_num: 30
    dropout: 0.1
    num_block: 16
    max_seq_len: 200
    temperature: 0.1
    loss_configs: [
      {"type": "info_nce", "weight": 1.0}
    ]

training_params:
  epochs: 300
  learning_rate: 0.001
  t_max: 10
  model_save_root_path: model_saves